server.xml.erb:
  target: /usr/local/tomcat/conf/server.xml
  config:
    port: 8080

application.properties.erb:
  target: /var/lib/application/application.properties
  config:
    metrics_reporterType: "DATADOG"
    metrics_environment: "DEV"
    metrics_apiKey: "your-key" cb97026e8a2bc9827669c8a2a5bcc582

logbackConfig.groovy.erb:
  target: /var/lib/application/logbackConfig.groovy
  
catalina.properties.erb:
  target: /usr/local/tomcat/conf/catalina.properties
